# Generated by Django 5.1.2 on 2025-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("political_leaning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="question_11",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_12",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_13",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_14",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_15",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_16",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_17",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_18",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_19",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question_20",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
