version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 political_leaning_bot.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/political_leaning
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=political_leaning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: